### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by MatteoJoliveau** [traduora/traduora#75]
**Is your feature request related to a problem? Please describe.**
Our stack is based on PostgreSQL as our primary datastore. We would love to use one of the existing server instances for our Traduora deployment instead of having to provision a MySQL instance just for it.

**Describe the solution you'd like**
Ideally, since TypeORM supports different database systems, we could find a way to keep Traduora agnostic and let the users pick the database they want.

**Describe alternatives you've considered**
I could fork the repo and replace MySQL's config with Postgre's one, but it would be hacky and less useful for other users.

I'm willing to try and implement this if there is enough interest from the community and the maintainers.

**Comment by azlux** [comment]
It's look like TypeORM support everything.
So the only line you need to change is: https://github.com/ever-co/ever-traduora/blob/2f61214264170f76fe8649920c2e87278f4cf3cf/api/src/config.ts#L50 with a new environment variable.

**Comment by peh** [comment]
The merged PR does not fully fix this issue in my eyes as trying to run the application with postgres as DB_TYPE results in 
`DriverPackageNotInstalledError: Postgres package has not been found installed. Try to install it: npm install pg --save`

**Comment by peh** [comment]
`Data type "binary" in "User.encryptedPassword" is not supported by "postgres" database.`

this is far as I come...

**Comment by oldluke92** [comment]
> this is far as I come...

I also stopped here. I guess it would be possible to use postgres 'bytea' column type instead of 'binary' but that would require to change the column type based on which DB is used.

**Comment by oldluke92** [comment]
I went ahead and replaced "binary" with "bytea". Next stop is migrations
```
Migration "addLocales1537531930470" failed, error: syntax error at or near "`"
/opt/traduora/node_modules/typeorm/error/TypeORMError.js:9
        var _this = _super.call(this, message) || this;
                           ^

QueryFailedError: syntax error at or near "`"
    at QueryFailedError.TypeORMError [as constructor] (/opt/traduora/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/opt/traduora/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at PostgresQueryRunner.<anonymous> (/opt/traduora/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:281:31)
    at step (/opt/traduora/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/opt/traduora/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
    at rejected (/opt/traduora/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  query: 'CREATE TABLE IF NOT EXISTS `locale` (`code` varchar(255) NOT NULL, `language` varchar(255) NOT NULL, `region` varchar(255) NOT NULL, `dateCreated` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), `dateModified` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (`code`)) ENGINE=InnoDB',
```

Giving up for now.

**Comment by csampaio26** [comment]
> The merged PR does not fully fix this issue in my eyes as trying to run the application with postgres as DB_TYPE results in `DriverPackageNotInstalledError: Postgres package has not been found installed. Try to install it: npm install pg --save`

How did you fix this?

**Comment by oldluke92** [comment]
Hey there,
as my pevious comments show - not at all really.
I built a new docker that has the pg package installed aswell as some db type replacements in the code. Did not invest too much time and therefor did not get it running with postgres anyways. I spun up a seperate mysql instance instead.

**Comment by evereq** [comment]
@csampaio26 / @oldluke92 not sure you saw, we have PR https://github.com/ever-co/ever-traduora/pull/391 by @vvadymk, however it's not yet finalized.

**Comment by vvadymk** [comment]
> @csampaio26 / @oldluke92 not sure you saw, we have PR #391 by @vvadymk, however it's not yet finalized.

Yes, it is still in progress.

**Comment by oldluke92** [comment]
@evereq and @vvadymk Thank you for your work on this!

However I ran into a few issues building the current develop branch (see https://github.com/ever-co/ever-traduora/issues/459, also had to add 
`
      ssl: true,
      extra: {
        ssl: {
          rejectUnauthorized: false,
        }
      },
`
to api/src/config.ts to support ssl on postgresql.

Afterwards the image built fine but I had weird behaviour in the UI (e.g. when clicking "new Project" the whole page got disabled and I could not use the dialog to fill in info)

I also saw that there has not been an official image for a few months. I would love to use traduora with postgres though.

EDIT: The UI misbehaviour was my own fault. We got a patch in the build that adds offline fonts which broke webapp/src/custom_bootstrap.scss. Looking all good now. (with the ssl lines still in place too. This should maybe be configurable though ...)

**Comment by evereq** [comment]
@oldluke92  I think `ssl: true, extra: { ssl: { rejectUnauthorized: false, } }` might be needed only if your DB require SSL but certificate is invalid or something like that. Are you running docker compose or how do you run app?

**Comment by oldluke92** [comment]
Hi,
for sure. Running in k8s using internal-ca signed certs.
Could ofc make the CA a trusted CA for the traduora container - but currently this is just testing.
Postgres has ssl set to required though.
So ssl: true is a must because traduora will otherwise be unable to connect, see  https://github.com/ever-co/ever-traduora/issues/338

**Comment by evereq** [comment]
OK, get it, we will add support for SSL for PG to Traduora, we have it in all other projects already :) 
Also, I just pushed latest docker images / released new version, so feel free to try it @oldluke92

**Comment by oldluke92** [comment]
Hi there.
coming back to this because a colleague poked me on this :D
As far as I remember I tried back in April 2025 and the image published then was still unable to connect to a DB with self-signed/untrusted certificate. A lot of self-hosted postgres dbs run with ssl required but self-signed cert. The default for postgres clients is to connect anyways if sslmode=required is set (untrusted encryption is better than no encryption ^^)
Is there any changes here ?
